import cv2
# MEMBACA GAMBAR DENGAN OPEN CV DAN PIL 
citra = cv2.imread("C:/Users/hp/Desktop/Pengolahan citra digital/kode program/Quiz-pcd.jpg")
cv2.imshow("quiz-blue", citra[:,:,0])
cv2.imshow("quiz-green", citra[:,:,1])
cv2.imshow("quiz-reed", citra[:,:,2])

cv2.waitKey()
# MELAKUKAN EDGE DETECTION MENGGUNAKAN SOBEL DAN CANNY

# MELAKUKAN CROPPING RANDOM CROPPING DAN HALF-SIZE CENTER CROPPING

# MELAKUKAN TRANSFORMASI DARI GAMBAR PUTIH JADI HITAM DAN HITAM JADI PUTIH

# MENAMBAHKAN NOISE PADA GAMBAR ORIGINAL , SALT AND PAPPER NOISE

# MELAKUKAN TRANSFOMASI GEOMETRI, ROTASI, FILIP VERTIKAL DAN HORIZONTAL